In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

df = pd.read_csv("../data/cleaned_churn.csv")

In [3]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,MonthlyCharges,TotalCharges,Churn,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,InternetService_Fiber optic,InternetService_No
0,0,0,1,0,1,0,0,0,1,0,...,29,29,0,0,0,0,1,0,0,0
1,1,0,0,0,34,1,0,1,0,1,...,56,1889,0,1,0,0,0,1,0,0
2,1,0,0,0,2,1,0,1,1,0,...,53,108,1,0,0,0,0,1,0,0
3,1,0,0,0,45,0,0,1,0,1,...,42,1840,0,1,0,0,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,70,151,1,0,0,0,1,0,1,0

In [6]:
df['AvgSpend'] = df['TotalCharges'] / (df['tenure'] + 1)

In [7]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,TotalCharges,Churn,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,InternetService_Fiber optic,InternetService_No,AvgSpend
0,0,0,1,0,1,0,0,0,1,0,...,29,0,0,0,0,1,0,0,0,14.500000
1,1,0,0,0,34,1,0,1,0,1,...,1889,0,1,0,0,0,1,0,0,53.971429
2,1,0,0,0,2,1,0,1,1,0,...,108,1,0,0,0,0,1,0,0,36.000000
3,1,0,0,0,45,0,0,1,0,1,...,1840,0,1,0,0,0,0,0,0,40.000000
4,0,0,0,0,2,1,0,0,0,0,...,151,1,0,0,0,1,0,1,0,50.333333

In [8]:
df['TenureGroup'] = pd.cut(df['tenure'],
                          bins=[0,12,24,48,72],
                          labels=['0-1yr','1-2yr','2-4yr','4-6yr'])

In [9]:
df = pd.get_dummies(df, columns=['TenureGroup'], drop_first=True)

In [12]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,InternetService_Fiber optic,InternetService_No,AvgSpend,TenureGroup_1-2yr,TenureGroup_2-4yr,TenureGroup_4-6yr
0,0,0,1,0,1,0,0,0,1,0,...,0,0,1,0,0,0,14,0,0,0
1,1,0,0,0,34,1,0,1,0,1,...,0,0,0,1,0,0,53,0,1,0
2,1,0,0,0,2,1,0,1,1,0,...,0,0,0,1,0,0,36,0,0,0
3,1,0,0,0,45,0,0,1,0,1,...,0,0,0,0,0,0,40,0,1,0
4,0,0,0,0,2,1,0,0,0,0,...,0,0,1,0,1,0,50,0,0,0

In [11]:
df = df.astype(int)

In [ ]:
from sklearn.model_selection import train_test_split